### ISSUE TITLE
No refunds

### ISSUE THREAD

**Issue by MSEMOBTC** [join4join/.github#1]
I don´t get 0.5 coins refunded for users leaving my server before 4d anymore

**Comment by warstrolo** [comment]
Hello, we are working on a fix, that will patch this issue
Please note that refund is not instant

With pleasure the join4join team

**Comment by warstrolo** [comment]
A patch has been deployed, we are monitoring, if this issue repeat please let us know

**Comment by warstrolo** [comment]
Since we do not have other reports, we are closing this issue
