### ISSUE TITLE
[BUG] Check feature bug 

### ISSUE THREAD

**Issue by queenadrianna** [join4join/.github#2]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**
 

**Additional context**

 - Device: [e.g. iPhone10]
When I try to leave servers after 4-5 days I can’t leave it by the bot because it says that the bot is not in the server and I cant leave it Manually because the picture of the servers don’t show up so I don’t know which servers to leave so if I leave a server I lose coins

![1F4952C9-EFD3-460F-AE04-A41907B2856E](https://user-images.githubusercontent.com/82171215/144711928-7705903b-bb9e-49e3-ab2c-29d94209a12b.png)

**Comment by warstrolo** [comment]
Hi, @queenadrianna thank you for the bug report we are patching this issue

**Comment by warstrolo** [comment]
Hi, @queenadrianna we have deployed the new version, we are monitoring the fix, can you tell us if the issue persist ?
